version: "3.3"
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      # It would be nice here to support OSes that don't have /tmp
      # See: https://github.com/docker/compose/issues/3344
      - "/tmp/var_lib_postgresql_data:/var/lib/postgresql/data"
  cms_test:
    container_name: cms_test
    build: .
    depends_on:
      - "db"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-testdb.conf
    volumes:
      - "./codecov:/home/cmsuser/cms/codecov"
    ports:
      - 8888:8888
      - 8889:8889
      - 8890:8890
    privileged: true
    command: >
      wait-for-it db:5432 -- sh -c "
      createdb --host=db --username=postgres cmsdb ;
      createdb --host=db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      sudo chown cmsuser:cmsuser ./codecov ;
      sudo apt install iputils-ping -y;
      sudo chmod 777 /usr/local/lib/python3.8/dist-packages/cms-1.5.dev0-py3.8.egg/cms/grading/Sandbox.py;
      sudo sed -i 's/self.cgroup = config.use_cgroups  # --cg/#self.cgroup = config.use_cgroups  # --cg/g' /usr/local/lib/python3.8/dist-packages/cms-1.5.dev0-py3.8.egg/cms/grading/Sandbox.py; 
      ping 8.8.8.8;
      #TEST_SUITE=unittests cmsRunTests -v --coverage codecov/unittests.xml ;
      #TEST_SUITE=functionaltests cmsRunTests -v --coverage codecov/functionaltests.xml ;
      "
